version: '3'
services:
  pgDB:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  db_data: